# Generated by Django 4.2.5 on 2023-09-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_courses', models.CharField(max_length=50, verbose_name='Название курсов')),
                ('preview_courses', models.ImageField(blank=True, null=True, upload_to='preview', verbose_name='Изображение')),
                ('description_courses', models.CharField(max_length=200, verbose_name='Название курсов')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
