# Generated by Django 4.2.5 on 2023-09-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('lesson_description', models.TextField(verbose_name='Описание')),
                ('lesson_preview', models.ImageField(blank=True, null=True, upload_to='static/lesson/', verbose_name='Превью')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.AlterField(
            model_name='courses',
            name='preview_courses',
            field=models.ImageField(blank=True, null=True, upload_to='static/preview', verbose_name='Изображение'),
        ),
    ]
